# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kadas_gpkg_import_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KadasGpkgImportDialog(object):
    def setupUi(self, KadasGpkgImportDialog):
        KadasGpkgImportDialog.setObjectName("KadasGpkgImportDialog")
        KadasGpkgImportDialog.resize(557, 230)
        self.gridLayout = QtWidgets.QGridLayout(KadasGpkgImportDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(KadasGpkgImportDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 2)
        self.labelDataWarning = QtWidgets.QLabel(KadasGpkgImportDialog)
        self.labelDataWarning.setWordWrap(True)
        self.labelDataWarning.setObjectName("labelDataWarning")
        self.gridLayout.addWidget(self.labelDataWarning, 1, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelInputFile = QtWidgets.QLabel(KadasGpkgImportDialog)
        self.labelInputFile.setObjectName("labelInputFile")
        self.horizontalLayout.addWidget(self.labelInputFile)
        self.lineEditInputFile = QtWidgets.QLineEdit(KadasGpkgImportDialog)
        self.lineEditInputFile.setReadOnly(True)
        self.lineEditInputFile.setObjectName("lineEditInputFile")
        self.horizontalLayout.addWidget(self.lineEditInputFile)
        self.buttonSelectFile = QtWidgets.QToolButton(KadasGpkgImportDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonSelectFile.sizePolicy().hasHeightForWidth())
        self.buttonSelectFile.setSizePolicy(sizePolicy)
        self.buttonSelectFile.setObjectName("buttonSelectFile")
        self.horizontalLayout.addWidget(self.buttonSelectFile)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.widgetProjectImport = QtWidgets.QWidget(KadasGpkgImportDialog)
        self.widgetProjectImport.setObjectName("widgetProjectImport")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgetProjectImport)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonImportProject = QtWidgets.QRadioButton(self.widgetProjectImport)
        self.radioButtonImportProject.setChecked(True)
        self.radioButtonImportProject.setObjectName("radioButtonImportProject")
        self.buttonGroupImport = QtWidgets.QButtonGroup(KadasGpkgImportDialog)
        self.buttonGroupImport.setObjectName("buttonGroupImport")
        self.buttonGroupImport.addButton(self.radioButtonImportProject)
        self.verticalLayout.addWidget(self.radioButtonImportProject)
        self.radioButtonImportLayers = QtWidgets.QRadioButton(self.widgetProjectImport)
        self.radioButtonImportLayers.setObjectName("radioButtonImportLayers")
        self.buttonGroupImport.addButton(self.radioButtonImportLayers)
        self.verticalLayout.addWidget(self.radioButtonImportLayers)
        self.listWidgetLayers = QtWidgets.QListWidget(self.widgetProjectImport)
        self.listWidgetLayers.setEnabled(False)
        self.listWidgetLayers.setIconSize(QtCore.QSize(16, 16))
        self.listWidgetLayers.setObjectName("listWidgetLayers")
        self.verticalLayout.addWidget(self.listWidgetLayers)
        self.gridLayout.addWidget(self.widgetProjectImport, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 2)

        self.retranslateUi(KadasGpkgImportDialog)
        self.buttonBox.accepted.connect(KadasGpkgImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(KadasGpkgImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(KadasGpkgImportDialog)

    def retranslateUi(self, KadasGpkgImportDialog):
        _translate = QtCore.QCoreApplication.translate
        KadasGpkgImportDialog.setWindowTitle(_translate("KadasGpkgImportDialog", "GPKG Import"))
        self.labelDataWarning.setText(_translate("KadasGpkgImportDialog", "<i>The selected GPKG does not contain a QGIS project, and will be imported as a layer.</i>"))
        self.labelInputFile.setText(_translate("KadasGpkgImportDialog", "Input file:"))
        self.buttonSelectFile.setText(_translate("KadasGpkgImportDialog", "Browse"))
        self.radioButtonImportProject.setText(_translate("KadasGpkgImportDialog", "Load entire project"))
        self.radioButtonImportLayers.setText(_translate("KadasGpkgImportDialog", "Import only selected layers:"))
