# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cartouchedialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CartoucheDialog(object):
    def setupUi(self, CartoucheDialog):
        CartoucheDialog.setObjectName("CartoucheDialog")
        CartoucheDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CartoucheDialog.resize(521, 566)
        self.gridLayout = QtWidgets.QGridLayout(CartoucheDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.mapcartoucheView = QtWidgets.QGraphicsView(CartoucheDialog)
        self.mapcartoucheView.setEnabled(False)
        self.mapcartoucheView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mapcartoucheView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.mapcartoucheView.setObjectName("mapcartoucheView")
        self.gridLayout.addWidget(self.mapcartoucheView, 17, 0, 1, 1)
        self.exerciseGroupBox = QtWidgets.QGroupBox(CartoucheDialog)
        self.exerciseGroupBox.setCheckable(True)
        self.exerciseGroupBox.setChecked(False)
        self.exerciseGroupBox.setObjectName("exerciseGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.exerciseGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.exerciseGroupBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.exercisedateLE = QtWidgets.QDateEdit(self.frame)
        self.exercisedateLE.setCalendarPopup(True)
        self.exercisedateLE.setObjectName("exercisedateLE")
        self.gridLayout_3.addWidget(self.exercisedateLE, 1, 0, 1, 1)
        self.coursetitleLE = QtWidgets.QLineEdit(self.frame)
        self.coursetitleLE.setObjectName("coursetitleLE")
        self.gridLayout_3.addWidget(self.coursetitleLE, 3, 0, 1, 1)
        self.exercisetitleLE = QtWidgets.QLineEdit(self.frame)
        self.exercisetitleLE.setObjectName("exercisetitleLE")
        self.gridLayout_3.addWidget(self.exercisetitleLE, 2, 2, 1, 1)
        self.documenttitleLE = QtWidgets.QLineEdit(self.frame)
        self.documenttitleLE.setObjectName("documenttitleLE")
        self.gridLayout_3.addWidget(self.documenttitleLE, 3, 2, 1, 1)
        self.classification1 = QtWidgets.QComboBox(self.frame)
        self.classification1.setEditable(True)
        self.classification1.setObjectName("classification1")
        self.gridLayout_3.addWidget(self.classification1, 1, 2, 1, 1)
        self.exerciseorganisationLE = QtWidgets.QLineEdit(self.frame)
        self.exerciseorganisationLE.setObjectName("exerciseorganisationLE")
        self.gridLayout_3.addWidget(self.exerciseorganisationLE, 2, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout.addWidget(self.exerciseGroupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(CartoucheDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 18, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(CartoucheDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.supplementtitleLE = QtWidgets.QLineEdit(self.frame_2)
        self.supplementtitleLE.setObjectName("supplementtitleLE")
        self.gridLayout_4.addWidget(self.supplementtitleLE, 5, 0, 1, 2)
        self.cartouchecircumscriptionLE = QtWidgets.QLineEdit(self.frame_2)
        self.cartouchecircumscriptionLE.setObjectName("cartouchecircumscriptionLE")
        self.gridLayout_4.addWidget(self.cartouchecircumscriptionLE, 4, 0, 1, 2)
        self.classification2 = QtWidgets.QComboBox(self.frame_2)
        self.classification2.setEditable(True)
        self.classification2.setObjectName("classification2")
        self.gridLayout_4.addWidget(self.classification2, 0, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 7, 0, 1, 1)
        self.placedateLE = QtWidgets.QLineEdit(self.frame_2)
        self.placedateLE.setObjectName("placedateLE")
        self.gridLayout_4.addWidget(self.placedateLE, 1, 1, 1, 1)
        self.codenameLE = QtWidgets.QLineEdit(self.frame_2)
        self.codenameLE.setObjectName("codenameLE")
        self.gridLayout_4.addWidget(self.codenameLE, 2, 0, 1, 2)
        self.troopstitleLE = QtWidgets.QLineEdit(self.frame_2)
        self.troopstitleLE.setObjectName("troopstitleLE")
        self.gridLayout_4.addWidget(self.troopstitleLE, 1, 0, 1, 1)
        self.scaletitleLE = QtWidgets.QLineEdit(self.frame_2)
        self.scaletitleLE.setInputMask("")
        self.scaletitleLE.setObjectName("scaletitleLE")
        self.gridLayout_4.addWidget(self.scaletitleLE, 6, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)

        self.retranslateUi(CartoucheDialog)
        self.classification1.setCurrentIndex(-1)
        self.classification2.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(CartoucheDialog.accept)
        self.buttonBox.rejected.connect(CartoucheDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CartoucheDialog)
        CartoucheDialog.setTabOrder(self.exerciseGroupBox, self.exercisedateLE)
        CartoucheDialog.setTabOrder(self.exercisedateLE, self.classification1)
        CartoucheDialog.setTabOrder(self.classification1, self.exerciseorganisationLE)
        CartoucheDialog.setTabOrder(self.exerciseorganisationLE, self.exercisetitleLE)
        CartoucheDialog.setTabOrder(self.exercisetitleLE, self.coursetitleLE)
        CartoucheDialog.setTabOrder(self.coursetitleLE, self.documenttitleLE)
        CartoucheDialog.setTabOrder(self.documenttitleLE, self.classification2)
        CartoucheDialog.setTabOrder(self.classification2, self.troopstitleLE)
        CartoucheDialog.setTabOrder(self.troopstitleLE, self.placedateLE)
        CartoucheDialog.setTabOrder(self.placedateLE, self.codenameLE)
        CartoucheDialog.setTabOrder(self.codenameLE, self.cartouchecircumscriptionLE)
        CartoucheDialog.setTabOrder(self.cartouchecircumscriptionLE, self.supplementtitleLE)
        CartoucheDialog.setTabOrder(self.supplementtitleLE, self.scaletitleLE)
        CartoucheDialog.setTabOrder(self.scaletitleLE, self.mapcartoucheView)
        CartoucheDialog.setTabOrder(self.mapcartoucheView, self.buttonBox)

    def retranslateUi(self, CartoucheDialog):
        _translate = QtCore.QCoreApplication.translate
        CartoucheDialog.setWindowTitle(_translate("CartoucheDialog", "Map Cartouche"))
        self.exerciseGroupBox.setTitle(_translate("CartoucheDialog", "Exercise"))
        self.coursetitleLE.setPlaceholderText(_translate("CartoucheDialog", "Course name"))
        self.exercisetitleLE.setPlaceholderText(_translate("CartoucheDialog", "Exercise name"))
        self.documenttitleLE.setPlaceholderText(_translate("CartoucheDialog", "Document name"))
        self.exerciseorganisationLE.setPlaceholderText(_translate("CartoucheDialog", "Exercise organisation"))
        self.supplementtitleLE.setPlaceholderText(_translate("CartoucheDialog", "Annex name"))
        self.cartouchecircumscriptionLE.setPlaceholderText(_translate("CartoucheDialog", "Title of cartouche"))
        self.placedateLE.setPlaceholderText(_translate("CartoucheDialog", "Place, date"))
        self.codenameLE.setPlaceholderText(_translate("CartoucheDialog", "\"CODE NAME\""))
        self.troopstitleLE.setPlaceholderText(_translate("CartoucheDialog", "Unit"))
        self.scaletitleLE.setPlaceholderText(_translate("CartoucheDialog", "Scale information"))
