# Form implementation generated from reading ui file 'printlayoutmanager.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PrintLayoutManager(object):
    def setupUi(self, PrintLayoutManager):
        PrintLayoutManager.setObjectName("PrintLayoutManager")
        PrintLayoutManager.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(PrintLayoutManager)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonImport = QtWidgets.QPushButton(parent=PrintLayoutManager)
        self.pushButtonImport.setObjectName("pushButtonImport")
        self.gridLayout.addWidget(self.pushButtonImport, 1, 0, 1, 1)
        self.pushButtonExport = QtWidgets.QPushButton(parent=PrintLayoutManager)
        self.pushButtonExport.setEnabled(False)
        self.pushButtonExport.setObjectName("pushButtonExport")
        self.gridLayout.addWidget(self.pushButtonExport, 1, 1, 1, 1)
        self.pushButtonRemove = QtWidgets.QPushButton(parent=PrintLayoutManager)
        self.pushButtonRemove.setEnabled(False)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.gridLayout.addWidget(self.pushButtonRemove, 1, 2, 1, 1)
        self.listWidgetLayouts = QtWidgets.QListWidget(parent=PrintLayoutManager)
        self.listWidgetLayouts.setObjectName("listWidgetLayouts")
        self.gridLayout.addWidget(self.listWidgetLayouts, 0, 0, 1, 3)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PrintLayoutManager)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 3)

        self.retranslateUi(PrintLayoutManager)
        self.buttonBox.accepted.connect(PrintLayoutManager.accept) # type: ignore
        self.buttonBox.rejected.connect(PrintLayoutManager.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PrintLayoutManager)

    def retranslateUi(self, PrintLayoutManager):
        _translate = QtCore.QCoreApplication.translate
        PrintLayoutManager.setWindowTitle(_translate("PrintLayoutManager", "Print Layout Manager"))
        self.pushButtonImport.setText(_translate("PrintLayoutManager", "Import"))
        self.pushButtonExport.setText(_translate("PrintLayoutManager", "Export"))
        self.pushButtonRemove.setText(_translate("PrintLayoutManager", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrintLayoutManager = QtWidgets.QDialog()
    ui = Ui_PrintLayoutManager()
    ui.setupUi(PrintLayoutManager)
    PrintLayoutManager.show()
    sys.exit(app.exec())
