name: Init Vcpkg
description: Init vcpkg environment
inputs:
  vcpkg-version:
    description: Enter vcpkg-tool version tag or latest
    required: false
    default: latest
    type: string

  vcpkg-root:
    description: Install vcpkg-tool into vcpkg-root
    required: false
    default: 'C:\vcpkg' # TODO: generalize for non windows OS
    type: string

runs:
  using: composite
  steps:
    - name: Init vcpkg
      shell: bash
      if: runner.os != 'Windows'
      run: |
        export VCPKG_ROOT=${{ inputs.vcpkg-root }}
        . <(curl https://aka.ms/vcpkg-init.sh -L)
        vcpkg --version
        echo "VCPKG_ROOT=${{ inputs.vcpkg-root }}" >> $GITHUB_ENV

    - name: Init vcpkg
      shell: pwsh
      if: runner.os == 'Windows'
      run: |
        $Env:VCPKG_ROOT = '${{ inputs.vcpkg-root }}'
        iex (iwr -useb https://aka.ms/vcpkg-init.ps1)
        vcpkg --version
        echo "VCPKG_ROOT=${{ inputs.vcpkg-root }}" >> $env:GITHUB_ENV
