---
name: 🏗️ Build
on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  release:
    types: ['published']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    uses: ./.github/workflows/build-docs.yml

  macos:
    needs: docs
    uses: ./.github/workflows/build-macos.yml
    with:
      docs-artifact-name: kadas-docs-html
    secrets: inherit

  windows:
    needs: docs
    uses: ./.github/workflows/build-windows.yml
    with:
      docs-artifact-name: kadas-docs-html
    secrets: inherit